select * from access$;

--Total Tables in ungremedy 2192
select count(*) from dba_tables;

--Views in DBA 7583
select count(*) from dba_views;

--Triggers in DBA 138
select count(*) from dba_triggers;

--SCRIPT
SELECT * FROM DBA_TABLES
WHERE TABLESPACE_NAME IN ('SYSAUX','SYSTEM')
ORDER BY TABLESPACE_NAME ASC;

SELECT TABLESPACE_NAME, MAX(PCT_FREE), MIN(PCT_FREE) FROM DBA_TABLES
WHERE TABLESPACE_NAME IN ('SYSAUX','SYSTEM')
GROUP BY TABLESPACE_NAME
ORDER BY TABLESPACE_NAME;

--DISTINCT TABLES IN DBA IS 2186 AS AT 28/07/2022
SELECT DISTINCT(TABLE_NAME) FROM DBA_TABLES
ORDER BY TABLE_NAME ASC;

--DBA VIEWS
SELECT * FROM DBA_VIEWS
ORDER BY VIEW_NAME;

--
SELECT * FROM DBA_TRIGGERS
WHERE TRIGGER_NAME='XDB_RV_TRIG';

SELECT * FROM DBA_TABLES
WHERE OWNER = 'SYS'
ORDER BY TABLE_NAME DESC;

SELECT DISTINCT(TABLE_NAME) FROM DBA_TABLES;
SELECT DISTINCT(OWNER) FROM DBA_TABLES;

SELECT COUNT(*) FROM DBA_SEQUENCES;

SELECT COUNT(*) FROM DBA_VIEWS;

SELECT COUNT(DISTINCT(TABLE_NAME)) AS UNIQUE_TABLE FROM DBA_TABLES;

SELECT COUNT(*) FROM DBA_TABLES;

SELECT * FROM ALL_USERS;
SELECT * FROM DBA_USERS;

SELECT * FROM DBA_TABLES
WHERE OWNER = 'SYS';

SELECT DISTINCT(OWNER) FROM DBA_TABLES;

SELECT * FROM DBA_ROLES;
SELECT DISTINCT(granted_role) FROM dba_role_privs;


SELECT * FROM dba_tablespaces;

USE ungremedy
SELECT * FROM dba_data_files
WHERE TABLESPACE_NAME='SYSTEM';

----SEGMENTS
SELECT * FROM DBA_SEGMENTS
WHERE SEGMENT_TYPE='TABLE' OR SEGMENT_TYPE='INDEX';


SELECT DISTINCT(TABLESPACE_NAME) FROM DBA_SEGMENTS;
SELECT DISTINCT(SEGMENT_TYPE) FROM DBA_SEGMENTS;
SELECT DISTINCT(OWNER) FROM DBA_SEGMENTS;
SELECT COUNT(DISTINCT(SEGMENT_NAME)) FROM DBA_SEGMENTS;

--DBA OBJECT
SELECT 
OWNER,OBJECT_NAME,OBJECT_ID,
DATA_OBJECT_ID,OBJECT_TYPE,
CREATED, LAST_DDL_TIME,STATUS
FROM DBA_OBJECTS;

SELECT * FROM DBA_TABLESPACES;

USE ungrdbox
SELECT Distinct(OWNER) FROM DBA_OBJECTS;

USE ungremedy
GO
SELECT OWNER AS TABLESPACE_OWNER,
OBJECT_TYPE,
CREATED AS CREATION_DATE,
STATUS AS OBJECT_STATUS,
TEMPORARY AS DB_TEMPORARY_STATE
FROM DBA_OBJECTS
WHERE TEMPORARY = 'Y';

--INDEX
SELECT * FROM DBA_INDEXES;

SELECT owner, index_name, index_type, table_owner FROM DBA_INDEXES
--WHERE INDEX_TYPE = 'NORMAL' AND TABLE_OWNER = 'SYS'
--GROUP BY INDEX_NAME
ORDER BY INDEX_NAME;

SELECT DISTINCT(INDEX_NAME) FROM DBA_INDEXES;
